version: '3.8'
services:
  appseed-app:
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    container_name: appseed_app
    depends_on:
      - db
    volumes:
      - .:/source
    expose:
      - "85"
    # links:
    #   - redis
    env_file:
      - ./.envs/.django
    networks:
      - djangonetwork
      - web_network

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - appseed-app
  db:
    image: postgres:15-alpine
    build:
      context: .
      dockerfile: compose/postgres/Dockerfile
    container_name: database
    env_file:
      - ./.envs/.postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    networks:
      - djangonetwork

  worker:
    env_file:
      - ./.envs/.django
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    container_name: worker
    command: celery worker --app core --loglevel info --logfile celery-worker.log
    volumes:
      - .:/source
    depends_on:
      - redis
    networks:
      - djangonetwork
  
  schedule:
    env_file:
      - ./.envs/.django
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    container_name: schedule
    command: celery beat --app core --loglevel info --logfile celery-beat.log
    volumes:
      - .:/source
    depends_on:
      - redis
    networks:
      - djangonetwork
  redis:
    image: "redis"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge
  web_network:
    driver: bridge
volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}